source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'LKRichTextEditor_Example' do
  pod 'LKRichTextEditor', :path => '../'
  pod 'Masonry', '~> 1.1.0'
#  pod 'IQKeyboardManager', '~> 6.5.16'
  target 'LKRichTextEditor_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
